<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    
    <xacro:property name="piperdius" value="0.1" />
    <xacro:property name="pipelen" value="0.4" />

    <xacro:macro name="link_macro" params="name x_origin y_origin z_origin color">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder length="${pipelen}" radius="${piperdius}"/>
                </geometry>
                <origin rpy="0 ${pi / 2.0} ${pi / 2.0}" xyz="${x_origin} ${y_origin} ${z_origin}"/>
                <material name="${color}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${pipelen}" radius="${piperdius}"/>
                </geometry>
                <origin rpy="0 ${pi / 2.0} ${pi / 2.0}" xyz="${x_origin} ${y_origin} ${z_origin}"/>
            </collision>
            <xacro:cylinder_inertia  m="1" r="${piperdius}" h="${pipelen}" xyz="${x_origin} ${y_origin} ${z_origin}" rpy="0 ${pi / 2.0} ${pi / 2.0}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="link_to_link_Zaxis_macro" params="name x_origin y_origin z_origin parent child">
        <joint name="${name}" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="1000.0" lower="-${pi / 2.0}" upper="${pi / 2.0}" velocity="0.5"/>
            <parent link="${parent}"/>
            <child link="${child}"/>
            <origin xyz="${x_origin} ${y_origin} ${z_origin}"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="link_to_link_Xaxis_macro" params="name x_origin y_origin z_origin parent child">
        <joint name="${name}" type="revolute">
            <axis xyz="1 0 0"/>
            <limit effort="1000.0" lower="-${pi / 2.0}" upper="${pi / 2.0}" velocity="0.5"/>
            <parent link="${parent}"/>
            <child link="${child}"/>
            <origin xyz="${x_origin} ${y_origin} ${z_origin}"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="connector_macro" params="postfix">
        <link name="connector${postfix}">
            <visual>
            <geometry>
                <sphere radius="${piperdius}"/>
            </geometry>
            <material name="red"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${piperdius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <xacro:sphere_inertia  m="0.5" r="${piperdius}" xyz="0 0 0" rpy="0 0 0"/>
        </link>
    </xacro:macro>

    <xacro:macro name="connector_to_link_macro" params="name x_origin y_origin z_origin parent child">
        <joint name="${name}" type="fixed">
            <parent link="${parent}"/>
            <child link="${child}"/>
            <origin xyz="${x_origin} ${y_origin} ${z_origin}"/>
        </joint>
    </xacro:macro>



    <xacro:link_macro name="base_link" x_origin="0" y_origin="0" z_origin="${piperdius}" color="red"/>

    <xacro:link_to_link_Zaxis_macro name="base_to_link1_Zaxis" x_origin="0" y_origin="${pipelen / 2}" z_origin="${piperdius}" parent="base_link" child="link1"/>
    <xacro:link_macro name="link1" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="blue"/>

    <xacro:link_to_link_Xaxis_macro name="link1_to_link2_Xaxis" x_origin="0" y_origin="${pipelen}" z_origin="0" parent="link1" child="link2"/>
    <xacro:link_macro name="link2" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="red"/>
    
    <xacro:link_to_link_Zaxis_macro name="link2_to_link3_Zaxis" x_origin="0" y_origin="${pipelen}" z_origin="0" parent="link2" child="link3"/>
    <xacro:link_macro name="link3" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="blue"/>

    <xacro:link_to_link_Xaxis_macro name="link3_to_link4_Xaxis" x_origin="0" y_origin="${pipelen}" z_origin="0" parent="link3" child="link4"/>
    <xacro:link_macro name="link4" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="red"/>

    <xacro:link_to_link_Zaxis_macro name="link4_to_link5_Zaxis" x_origin="0" y_origin="${pipelen}" z_origin="0" parent="link4" child="link5"/>
    <xacro:link_macro name="link5" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="blue"/>

    <xacro:link_to_link_Xaxis_macro name="link5_to_link6_Xaxis" x_origin="0" y_origin="${pipelen}" z_origin="0" parent="link5" child="link6"/>
    <xacro:link_macro name="link6" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="red"/>

    <xacro:link_to_link_Zaxis_macro name="link6_to_link7_Zaxis" x_origin="0" y_origin="${pipelen}" z_origin="0" parent="link6" child="link7"/>
    <xacro:link_macro name="link7" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="blue"/>

    <xacro:link_to_link_Xaxis_macro name="link7_to_link8_Xaxis" x_origin="0" y_origin="${pipelen}" z_origin="0" parent="link7" child="link8"/>
    <xacro:link_macro name="link8" x_origin="0" y_origin="${pipelen / 2}" z_origin="0" color="red"/>
</robot>