controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
       
    effort_controllers:
      type: effort_controllers/JointGroupEffortController

joint_state_broadcaster:
   ros__parameters:
    joints:
      - ${base_to_link1_Zaxis_joint}
      - ${link1_to_link2_Xaxis_joint}
      - ${link2_to_link3_Zaxis_joint}
      - ${link3_to_link4_Xaxis_joint}
      - ${link4_to_link5_Zaxis_joint}
      - ${link5_to_link6_Xaxis_joint}
      - ${link6_to_link7_Zaxis_joint}
      - ${link7_to_link8_Xaxis_joint}

effort_controllers:
   ros__parameters:
    joints:
      - ${base_to_link1_Zaxis_joint}
      - ${link1_to_link2_Xaxis_joint}
      - ${link2_to_link3_Zaxis_joint}
      - ${link3_to_link4_Xaxis_joint}
      - ${link4_to_link5_Zaxis_joint}
      - ${link5_to_link6_Xaxis_joint}
      - ${link6_to_link7_Zaxis_joint}
      - ${link7_to_link8_Xaxis_joint}

    interface_name: effort
    
    command_interfaces:
      - effort 
    
    state_interfaces:
      - position
      - velocity
      - effort   